### ISSUE TITLE
Item conversion in the interface

### ISSUE THREAD

**Issue by TheBloodyTalon** [unascribed/CorrelatedPotentialistics#10]
If you place an item in the output slot, then add a different item into the configuration spot for the same output slot, you can then place in any of the configured item into the system or input slots and it will be converted into the output item.

https://www.youtube.com/watch?v=8d8hoUFGcfc
Here is a video of the bug in action, it's really quick.

**Comment by unascribed** [comment]
I see why this is happening... and it's quite dumb. Working on it for 0.2.2_01

**Comment by TheBloodyTalon** [comment]
Sounds great, I was just testing the mod out to try and put it on a server and just ran into the bug accidentally.  I'm glad I saw it.
