### ISSUE TITLE
when connecting enderio item conduits to interface it crashes

### ISSUE THREAD

**Issue by darkdata** [unascribed/CorrelatedPotentialistics#6]
when connecting enderio item conduits to interface it crashes

CorrelatedPotentialistics-0.2.1
EnderCore-1.8.9-0.3.0.13-beta
EnderIO-1.8.9-3.0.0.22_alpha

**Comment by unascribed** [comment]
Crash report?

**Comment by darkdata** [comment]
[crash-2016-04-08_17.31.55-server.txt](https://github.com/unascribed/CorrelatedPotentialistics/files/210893/crash-2016-04-08_17.31.55-server.txt)

**Comment by unascribed** [comment]
I'm currently working on things other than the mod, and can't build a release right now. It'll be included in the next release.

**Comment by darkdata** [comment]
no hurry and thank you
