### ISSUE TITLE
Crash when brakeing Controller (version 0.2.1)

### ISSUE THREAD

**Issue by GIGAAj1** [unascribed/CorrelatedPotentialistics#7]
---- Minecraft Crash Report ----

WARNING: coremods are present:
  CoreXU2 (extrautils2-1.8.9-alpha-0.0.2.jar)
  FMLPlugin (InventoryTweaks-1.60-40.jar)
  LoadingPlugin (NoNausea-MC1.8-1.0.jar)
  BookshelfLoadingPlugin (Bookshelf-1.8.9-1.1.2.207.jar)
  BIFLoader (BowInfinityFix-1.8.x-rv2.jar)
  NowWithRendering (redstonepaste-mc1.8.8-1.7.2.jar)
Contact their authors BEFORE contacting forge

// I just don't know what went wrong :(

Time: 09.04.16 17:35
Description: Rendering Block Entity

java.lang.IllegalArgumentException: Cannot get property PropertyEnum{name=state, clazz=class com.unascribed.correlatedpotentialistics.block.BlockController$State, values=[powered, off, error, booting]} as it does not exist in BlockState{block=minecraft:air, properties=[]}
	at net.minecraft.block.state.BlockState$StateImplementation.func_177229_b(BlockState.java:137)
	at com.unascribed.correlatedpotentialistics.client.render.RenderController.renderTileEntityAt(RenderController.java:26)
	at com.unascribed.correlatedpotentialistics.client.render.RenderController.func_180535_a(RenderController.java:19)
	at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.func_178469_a(TileEntityRendererDispatcher.java:136)
	at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.func_180546_a(TileEntityRendererDispatcher.java:114)
	at net.minecraft.client.renderer.RenderGlobal.func_180446_a(RenderGlobal.java:900)
	at shadersmod.client.ShadersRender.renderShadowMap(ShadersRender.java:343)
	at shadersmod.client.Shaders.beginRender(Shaders.java:3637)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1522)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1328)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1051)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:349)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at net.minecraft.block.state.BlockState$StateImplementation.func_177229_b(BlockState.java:137)
	at com.unascribed.correlatedpotentialistics.client.render.RenderController.renderTileEntityAt(RenderController.java:26)
	at com.unascribed.correlatedpotentialistics.client.render.RenderController.func_180535_a(RenderController.java:19)

-- Block Entity Details --
Details:
	Name: correlatedpotentialistics:controller // com.unascribed.correlatedpotentialistics.tile.TileEntityController
	Block type: ID #527 (tile.correlatedpotentialistics.controller // com.unascribed.correlatedpotentialistics.block.BlockController)
	Block data value: 0 / 0x0 / 0b0000
	Block location: World: (-232,71,155), Chunk: (at 8,4,11 in -15,9; contains blocks -240,0,144 to -225,255,159), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Actual block type: ID #0 (tile.air // net.minecraft.block.BlockAir)
	Actual block data value: 0 / 0x0 / 0b0000
Stacktrace:
	at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.func_178469_a(TileEntityRendererDispatcher.java:136)
	at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.func_180546_a(TileEntityRendererDispatcher.java:114)
	at net.minecraft.client.renderer.RenderGlobal.func_180446_a(RenderGlobal.java:900)
	at shadersmod.client.ShadersRender.renderShadowMap(ShadersRender.java:343)
	at shadersmod.client.Shaders.beginRender(Shaders.java:3637)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1522)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['GIGAAj1'/2776, l='MpServer', x=-231,37, y=71,00, z=157,16]]
	Chunk stats: MultiplayerChunkCache: 289, 289
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: 8,00,64,00,8,00 - World: (8,64,8), Chunk: (at 8,4,8 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 360909 game time, 152811 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 93 total; [EntityBat['Bat'/312582, l='MpServer', x=-270,25, y=41,10, z=130,75], EntityZombie['Zombie'/319233, l='MpServer', x=-171,97, y=19,00, z=97,50], EntityPig['Pig'/2569, l='MpServer', x=-303,94, y=66,00, z=141,00], EntitySheep['Sheep'/88331, l='MpServer', x=-244,63, y=76,00, z=121,09], EntityPig['Pig'/2570, l='MpServer', x=-299,47, y=65,00, z=140,06], EntityPig['Pig'/2571, l='MpServer', x=-301,56, y=66,00, z=137,44], EntitySkeleton['Skeleton'/304136, l='MpServer', x=-249,50, y=43,00, z=113,50], EntityPig['Pig'/2573, l='MpServer', x=-294,91, y=68,00, z=144,56], EntityPig['Pig'/2574, l='MpServer', x=-277,16, y=71,00, z=140,72], EntitySheep['Sheep'/88334, l='MpServer', x=-228,34, y=78,00, z=100,25], EntityPig['Pig'/2575, l='MpServer', x=-293,56, y=69,00, z=155,69], EntityZombie['Zombie'/317707, l='MpServer', x=-301,69, y=21,00, z=120,13], EntityPig['Pig'/2576, l='MpServer', x=-293,94, y=70,00, z=187,94], EntityPig['Pig'/88336, l='MpServer', x=-221,31, y=72,00, z=142,53], EntityPig['Pig'/2577, l='MpServer', x=-295,19, y=69,00, z=209,44], EntityPig['Pig'/2578, l='MpServer', x=-289,88, y=71,00, z=213,13], EntitySkeleton['Skeleton'/318480, l='MpServer', x=-185,50, y=46,00, z=217,50], EntityPig['Pig'/2581, l='MpServer', x=-285,28, y=70,00, z=152,84], EntitySkeleton['Skeleton'/336415, l='MpServer', x=-175,50, y=40,00, z=186,50], EntitySheep['Sheep'/88348, l='MpServer', x=-196,03, y=77,00, z=101,00], EntityHuman['Ted'/2590, l='MpServer', x=-261,91, y=72,88, z=171,53], EntitySheep['Sheep'/88350, l='MpServer', x=-204,06, y=76,00, z=120,03], EntityCreeper['Creeper'/312868, l='MpServer', x=-171,50, y=23,00, z=163,50], EntityHuman['Saige'/2601, l='MpServer', x=-260,63, y=72,00, z=168,69], EntityHuman['Star'/2602, l='MpServer', x=-240,41, y=71,00, z=166,22], EntityHuman['Adam'/2603, l='MpServer', x=-215,22, y=68,00, z=183,56], EntitySheep['Sheep'/88362, l='MpServer', x=-189,56, y=75,00, z=121,31], EntitySpider['Spider'/314920, l='MpServer', x=-310,50, y=33,00, z=157,50], EntityHuman['Terry'/2605, l='MpServer', x=-251,57, y=68,42, z=187,73], EntityHuman['Amir'/2606, l='MpServer', x=-236,28, y=69,00, z=192,75], EntitySkeleton['Skeleton'/332330, l='MpServer', x=-186,94, y=21,00, z=198,41], EntityHuman['Candace'/2611, l='MpServer', x=-248,50, y=72,00, z=177,19], EntityCow['Cow'/2613, l='MpServer', x=-255,94, y=67,00, z=216,06], EntityBat['Bat'/336944, l='MpServer', x=-297,38, y=43,56, z=150,73], EntityHuman['Elijah'/2614, l='MpServer', x=-250,50, y=71,01, z=171,75], EntityHuman['Millie'/2618, l='MpServer', x=-232,72, y=71,00, z=155,56], EntityCreeper['Creeper'/326974, l='MpServer', x=-158,50, y=68,00, z=96,50], EntityHuman['Aj'/2619, l='MpServer', x=-235,16, y=71,00, z=163,50], EntityHuman['Zayne'/2620, l='MpServer', x=-247,56, y=69,00, z=198,88], EntityHuman['Cedric'/2621, l='MpServer', x=-255,69, y=68,00, z=190,28], EntityHuman['Brie'/2622, l='MpServer', x=-271,69, y=67,00, z=205,16], EntityHuman['Arran'/2623, l='MpServer', x=-244,72, y=69,00, z=205,06], EntityHuman['Jadyn'/2624, l='MpServer', x=-246,45, y=69,00, z=199,50], EntityHuman['Kailyn'/2625, l='MpServer', x=-250,50, y=71,00, z=170,96], EntitySkeleton['Skeleton'/328516, l='MpServer', x=-266,50, y=32,00, z=91,50], EntityHuman['Walker'/2626, l='MpServer', x=-255,22, y=70,00, z=184,50], EntityZombie['Zombie'/328519, l='MpServer', x=-182,50, y=15,00, z=168,50], EntityHuman['Erin'/2627, l='MpServer', x=-242,31, y=69,00, z=205,38], EntityCreeper['Creeper'/322113, l='MpServer', x=-227,50, y=13,00, z=162,50], EntityHuman['Nola'/2633, l='MpServer', x=-236,63, y=69,00, z=185,78], EntityHuman['Leven'/2634, l='MpServer', x=-216,28, y=69,00, z=177,44], EntityZombie['Zombie'/299861, l='MpServer', x=-169,09, y=26,00, z=107,59], EntitySpider['Spider'/320855, l='MpServer', x=-202,50, y=17,00, z=179,50], EntityZombie['Zombie'/322137, l='MpServer', x=-183,50, y=11,00, z=100,50], EntitySheep['Sheep'/2655, l='MpServer', x=-204,97, y=68,00, z=184,06], EntityHorse['Horse'/2665, l='MpServer', x=-193,75, y=68,00, z=208,56], EntityItem['item.item.emerald'/298871, l='MpServer', x=-238,88, y=69,00, z=189,50], EntitySheep['Sheep'/2676, l='MpServer', x=-158,59, y=78,00, z=135,66], EntityCreeper['Creeper'/313712, l='MpServer', x=-177,50, y=29,00, z=166,50], EntityZombie['Zombie'/335229, l='MpServer', x=-281,50, y=19,00, z=86,50], EntitySheep['Sheep'/2685, l='MpServer', x=-161,84, y=80,00, z=204,78], EntitySheep['Sheep'/2686, l='MpServer', x=-164,56, y=77,00, z=227,31], EntityPig['Pig'/2689, l='MpServer', x=-174,97, y=80,00, z=237,09], EntityItem['item.item.bone'/288129, l='MpServer', x=-177,56, y=44,00, z=216,72], EntitySkeleton['Skeleton'/336259, l='MpServer', x=-308,50, y=47,00, z=163,50], EntitySheep['Sheep'/2698, l='MpServer', x=-154,06, y=78,00, z=132,00], EntitySheep['Sheep'/2703, l='MpServer', x=-159,53, y=90,00, z=223,56], EntitySheep['Sheep'/2704, l='MpServer', x=-156,59, y=77,00, z=234,66], EntityBat['Bat'/328870, l='MpServer', x=-238,73, y=49,21, z=107,52], EntityBat['Bat'/328866, l='MpServer', x=-306,52, y=20,50, z=193,44], EntityZombie['Zombie'/335272, l='MpServer', x=-253,50, y=13,00, z=226,50], EntityItem['item.item.bone'/284848, l='MpServer', x=-278,41, y=22,00, z=186,13], EntitySkeleton['Skeleton'/336305, l='MpServer', x=-179,50, y=38,00, z=188,50], EntityCreeper['Creeper'/329661, l='MpServer', x=-168,50, y=15,00, z=189,50], EntityZombie['Zombie'/316607, l='MpServer', x=-270,50, y=31,00, z=205,50], EntitySkeleton['Skeleton'/329657, l='MpServer', x=-156,50, y=22,00, z=144,50], EntitySkeleton['Skeleton'/335290, l='MpServer', x=-169,50, y=23,00, z=163,50], EntityZombie['Zombie'/321734, l='MpServer', x=-309,50, y=35,00, z=182,50], EntityItem['item.item.bone'/337602, l='MpServer', x=-176,09, y=40,00, z=185,69], EntityBat['Bat'/331468, l='MpServer', x=-174,78, y=12,10, z=173,41], EntityBat['Bat'/324052, l='MpServer', x=-172,90, y=27,00, z=127,41], EntityPlayerSP['GIGAAj1'/2776, l='MpServer', x=-231,37, y=71,00, z=157,16], EntityBat['Bat'/314081, l='MpServer', x=-215,13, y=45,09, z=144,38], EntityBat['Bat'/333037, l='MpServer', x=-171,21, y=18,03, z=113,42], EntityPig['Pig'/88299, l='MpServer', x=-290,56, y=69,00, z=121,28], EntityHorse['Horse'/88298, l='MpServer', x=-299,69, y=71,00, z=125,28], EntityCow['Cow'/88300, l='MpServer', x=-303,25, y=77,00, z=124,41], EntityCow['Cow'/88308, l='MpServer', x=-271,63, y=70,00, z=120,63], EntityHorse['Horse'/88311, l='MpServer', x=-262,03, y=70,00, z=113,13], EntityHorse['Horse'/88313, l='MpServer', x=-281,00, y=69,00, z=109,66], EntityHorse['Horse'/88312, l='MpServer', x=-280,97, y=70,00, z=105,28], EntityPig['Pig'/2553, l='MpServer', x=-309,31, y=64,00, z=155,84], EntityZombie['Zombie'/319226, l='MpServer', x=-191,50, y=21,00, z=184,50]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:404)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2536)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:370)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.8.9
	Operating System: Windows 10 (amd64) version 10.0
	CPU: 4x AMD Processor model unknown
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 558923392 bytes (533 MB) / 2807562240 bytes (2677 MB) up to 3817865216 bytes (3641 MB)
	Mod Pack: 1.8.9-SNAPSHOT-r7347BFE-b7-2016-03-04_11-41-28
	LiteLoader Mods: 1 loaded mod(s)
          - VoxelMap version 1.6.1
	LaunchWrapper: 31 active transformer(s)
          - Transformer: net.minecraftforge.fml.common.asm.transformers.PatchingTransformer
          - Transformer: optifine.OptiFineClassTransformer
          - Transformer: $wrapper.net.minecraftforge.fml.common.asm.transformers.BlamingTransformer
          - Transformer: $wrapper.net.minecraftforge.fml.common.asm.transformers.SideTransformer
          - Transformer: $wrapper.net.minecraftforge.fml.common.asm.transformers.EventSubscriptionTransformer
          - Transformer: $wrapper.net.minecraftforge.fml.common.asm.transformers.EventSubscriberTransformer
          - Transformer: $wrapper.invtweaks.forge.asm.ContainerTransformer
          - Transformer: $wrapper.net.fybertech.nwr.NowWithRendering
          - Transformer: org.spongepowered.asm.mixin.transformer.MixinTransformer$Proxy
          - Transformer: com.mumfrey.liteloader.transformers.event.EventProxyTransformer
          - Transformer: com.mumfrey.liteloader.launch.LiteLoaderTransformer
          - Transformer: com.mumfrey.liteloader.client.transformers.CrashReportTransformer
          - Transformer: net.minecraftforge.fml.common.asm.transformers.DeobfuscationTransformer
          - Transformer: net.minecraftforge.fml.common.asm.transformers.AccessTransformer
          - Transformer: invtweaks.forge.asm.ITAccessTransformer
          - Transformer: net.minecraftforge.fml.common.asm.transformers.ModAccessTransformer
          - Transformer: net.minecraftforge.fml.common.asm.transformers.ItemStackTransformer
          - Transformer: org.spongepowered.asm.mixin.transformer.MixinTransformer$Proxy
          - Transformer: $wrapper.net.darkhax.bookshelf.asm.BookshelfTransformerManager
          - Transformer: $wrapper.com.github.parker8283.bif.Transformer
          - Transformer: $wrapper.lumien.nonausea.asm.ClassTransformer
          - Transformer: $wrapper.com.rwtema.extrautils2.asm.ClassTransformerHandler
          - Transformer: net.minecraftforge.fml.common.asm.transformers.TerminalTransformer
          - Transformer: org.spongepowered.asm.mixin.transformer.MixinTransformer$Proxy
          - Transformer: com.thevoxelbox.voxelmap.litemod.VoxelMapTransformer
          - Transformer: com.mumfrey.liteloader.transformers.event.EventTransformer
          - Transformer: com.mumfrey.liteloader.common.transformers.LiteLoaderPacketTransformer
          - Transformer: com.mumfrey.liteloader.client.transformers.MinecraftTransformer
          - Transformer: com.mumfrey.liteloader.transformers.event.json.ModEventInjectionTransformer
          - Transformer: org.spongepowered.asm.mixin.transformer.MixinTransformer$Proxy
          - Transformer: net.minecraftforge.fml.common.asm.transformers.ModAPITransformer
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx4096m -Xms256m -XX:PermSize=256m
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
	FML: MCP 9.19 Powered by Forge 11.15.1.1847 Optifine OptiFine_1.8.9_HD_U_H5 57 mods loaded, 57 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.8.9-11.15.1.1847.jar) 
	UCHIJAAAA	Forge{11.15.1.1847} [Minecraft Forge] (forge-1.8.9-11.15.1.1847.jar) 
	UCHIJAAAA	bowinfinityfix{rv2} [Bow Infinity Fix] (minecraft.jar) 
	UCHIJAAAA	cei{0.1} [Chunk Edge Indicator] (1.8.9-chunkedgeindicator-1.0.jar) 
	UCHIJAAAA	Baubles{1.1.3.0} [Baubles] (Baubles-1.8.9-1.1.3.0.jar) 
	UCHIJAAAA	baublesstuff{2.0.3} [Baubles Stuff] (baublesstuff-2.0.3.jar) 
	UCHIJAAAA	BetterAchievements{0.1.1} [Better Achievements] (BetterAchievements-1.8.9-0.1.1.jar) 
	UCHIJAAAA	bookshelf{1.1.2.207} [Bookshelf] (Bookshelf-1.8.9-1.1.2.207.jar) 
	UCHIJAAAA	Botania{r1.8-299} [Botania] (Botania-unofficial.r1.8-299.jar) 
	UCHIJAAAA	BuildCraft|Core{7.2.5} [BuildCraft] (buildcraft-7.2.5-core.jar) 
	UCHIJAAAA	BuildCraft|Builders{7.2.5} [BC Builders] (buildcraft-7.2.5-builders.jar) 
	UCHIJAAAA	BuildCraft|Energy{7.2.5} [BC Energy] (buildcraft-7.2.5-energy.jar) 
	UCHIJAAAA	BuildCraft|Factory{7.2.5} [BC Factory] (buildcraft-7.2.5-factory.jar) 
	UCHIJAAAA	BuildCraft|Transport{7.2.5} [BC Transport] (buildcraft-7.2.5-transport.jar) 
	UCHIJAAAA	chunkloaderz{1.0.3} [ChunkLoaderZ] (ChunkLoaderZ-1.8.9-1.0.3.jar) 
	UCHIJAAAA	correlatedpotentialistics{0.2.1} [Correlated Potentialistics] (CorrelatedPotentialistics-0.2.1.jar) 
	UCHIJAAAA	cosmeticarmorreworked{1.8.9-v2c} [CosmeticArmorReworked] (CosmeticArmorReworked-1.8.9-v2c.jar) 
	UCHIJAAAA	ExtraUtils2{1.0} [ExtraUtils2] (extrautils2-1.8.9-alpha-0.0.2.jar) 
	UCHIJAAAA	JEI{2.28.15.183} [Just Enough Items] (jei_1.8.9-2.28.15.183.jar) 
	UCHIJAAAA	Waila{1.6.0} [Waila] (Waila-1.6.0-B3_1.8.8.jar) 
	UCHIJAAAA	DarkUtils{1.0.0.9} [Dark Utilities] (DarkUtilities-1.8.9-1.0.0.18.jar) 
	UCHIJAAAA	Ding{MC1.8.9v2} [Ding] (Ding-MC1.8.9v2.jar) 
	UCHIJAAAA	endercompass{1.2.2} [Ender Compass] (EnderCompass-1.8.9-1.2.2.jar) 
	UCHIJAAAA	enderutilities{0.5.3} [Ender Utilities] (enderutilities-1.8.9-0.5.3.jar) 
	UCHIJAAAA	GlobalGameRules{1.0} [Global GameRules] (GlobalGameRules-1.8.9-1.0.jar) 
	UCHIJAAAA	guideapi{1.8.9-2.0.0-28} [Guide-API] (Guide-API-1.8.9-2.0.0-28.jar) 
	UCHIJAAAA	inventorytweaks{1.60-40-e06e29a} [Inventory Tweaks] (InventoryTweaks-1.60-40.jar) 
	UCHIJAAAA	IronChest{6.0.125.770} [Iron Chest] (ironchest-1.8.9-6.0.125.770.jar) 
	UCHIJAAAA	jacb{1.0.6} [JACB] (JACB-1.8.9-1.0.6.jar) 
	UCHIJAAAA	JEIAddons{0.12.0.57} [Just Enough Items Addons] (JEIAddons_1.8.9-0.12.0.57.jar) 
	UCHIJAAAA	magicclover{1.8-0.7.2} [Magic Clover] (magicclover-1.8-0.7.2.jar) 
	UCHIJAAAA	RadixCore{1.8.9-2.1.0} [RadixCore] (RadixCore-1.8.9-2.1.0-universal.jar) 
	UCHIJAAAA	MCA{1.8.9-5.1.2} [Minecraft Comes Alive] (MCA-1.8.9-5.1.2-universal.jar) 
	UCHIJAAAA	testdummy{1.0} [MmmMmmMmmMmm] (MmmMmmMmmMmm-1.9b.jar) 
	UCHIJAAAA	MoarRecipes{1.1} [MoarRecipes] (MoarRecipes-1.1-[1.8.9].jar) 
	UCHIJAAAA	Neat{GRADLE:VERSION-GRADLE:BUILD} [Neat] (Neat 1.1-3.jar) 
	UCHIJAAAA	nmsot{1.1.2-mc1.8.9} [No Mob Spawning on Trees] (NoMobSpawningOnTrees-1.1.2-mc1.8.9.jar) 
	UCHIJAAAA	recipehandler{0.3} [NoMoreRecipeConflict] (NoMoreRecipeConflict-0.3(1.8.X).jar) 
	UCHIJAAAA	NoNausea{1.0} [No Nausea] (NoNausea-MC1.8-1.0.jar) 
	UCHIJAAAA	progressiveautomation{1.6.35} [Progressive Automation] (ProgressiveAutomation-1.8.9-1.6.35.jar) 
	UCHIJAAAA	ProjectE{1.8.9-PE1.1.4} [ProjectE] (ProjectE-1.8.9-PE1.1.4.jar) 
	UCHIJAAAA	quantumflux{2.0.1} [QuantumFlux] (quantumflux-1.8.9-2.0.1.jar) 
	UCHIJAAAA	reborncore{1.5.1.57} [RebornCore] (RebornCore-1.8.9-1.5.1.57-universal.jar) 
	UCHIJAAAA	QuantumStorage{2.0.3} [QuantumStorage] (QuantumStorage-1.8.9-2.0.3.jar) 
	UCHIJAAAA	redstonepaste{1.7.2} [Redstone Paste] (redstonepaste-mc1.8.8-1.7.2.jar) 
	UCHIJAAAA	SoulShardsTOW{1.8.9-2.2.8-16} [Soul Shards - The Old Ways] (SoulShards-TOW-1.8.9-2.2.8-16.jar) 
	UCHIJAAAA	soundfilters{0.8_for_1.8} [Sound Filters] (SoundFilters-0.8_for_1.8.jar) 
	UCHIJAAAA	TbscFPS{2.1} [TbscFPS] (TbscFPS-2.1.jar) 
	UCHIJAAAA	uncraftingtable{1.0.2} [Uncrafting Grinder] (UncraftingGrinder-1.8.9-1.0.2.jar) 
	UCHIJAAAA	VeinMiner{0.31.4_build.unknown} [Vein Miner] (VeinMiner-1.8.9_0.31.4.unknown.jar) 
	UCHIJAAAA	VeinMinerModSupport{0.31.4_build.unknown} [Mod Support] (VeinMiner-1.8.9_0.31.4.unknown.jar) 
	UCHIJAAAA	WailaHarvestability{1.1.6} [Waila Harvestability] (WailaHarvestability-mc1.8.x-1.1.6.jar) 
	UCHIJAAAA	warpbook{2.0.43} [Warp Book] (warpbook-1.8.9_2.0.43.jar) 
	UCHIJAAAA	witherchargingfix{1.0.0} [Wither Charging Fix] (witherchargingfix-1.8.9-1.0.0-0-universal.jar) 
	UCHIJAAAA	xpstacker{1.0} [XP-Stacker] (Xp-Stacker-1.8.9-1.0.jar) 
	UCHIJAAAA	zoooooom{0.1.2} [Zoooooom] (Zoooooom-1.8.9-0.1.2.jar) 
	Loaded coremods (and transformers): 
CoreXU2 (extrautils2-1.8.9-alpha-0.0.2.jar)
  com.rwtema.extrautils2.asm.ClassTransformerHandler
FMLPlugin (InventoryTweaks-1.60-40.jar)
  invtweaks.forge.asm.ContainerTransformer
LoadingPlugin (NoNausea-MC1.8-1.0.jar)
  lumien.nonausea.asm.ClassTransformer
BookshelfLoadingPlugin (Bookshelf-1.8.9-1.1.2.207.jar)
  net.darkhax.bookshelf.asm.BookshelfTransformerManager
BIFLoader (BowInfinityFix-1.8.x-rv2.jar)
  com.github.parker8283.bif.Transformer
NowWithRendering (redstonepaste-mc1.8.8-1.7.2.jar)
  net.fybertech.nwr.NowWithRendering
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.5.0 NVIDIA 364.72' Renderer: 'GeForce GTX 660/PCIe/SSE2'
	Launched Version: forge-11.15.1.1847
	LWJGL: 2.9.4
	OpenGL: GeForce GTX 660/PCIe/SSE2 GL version 4.5.0 NVIDIA 364.72, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 4x AMD Processor model unknown
	OptiFine Version: OptiFine_1.8.9_HD_U_H5
	Render Distance Chunks: 8
	Mipmaps: 0
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: MrMeepz Shaders v05 UltraPlus.zip
	OpenGlVersion: 4.5.0 NVIDIA 364.72
	OpenGlRenderer: GeForce GTX 660/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 4

**Comment by unascribed** [comment]
Please use [Gist](https://gist.github.com) next time.

**Comment by GIGAAj1** [comment]
ok ^^
